services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      target: app
    image: ${APP_IMAGE:-heroes-app:latest}
    depends_on:
      - db
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
    volumes:
      - storage:/var/www/storage

  web:
    build:
      context: .
      target: web
    image: ${WEB_IMAGE:-heroes-web:latest}
    depends_on:
      - app
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - storage:/var/www/storage:ro

  caddy:
    image: caddy:2.8-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
      # Optional: provide ACME email to avoid rate limits
      # ACME_EMAIL: ${ACME_EMAIL}
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pgdata:
  storage:
  caddy_data:
  caddy_config:
