name: deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase owner
        id: vars
        shell: bash
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: app
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/heroes-app:latest
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/heroes-app:${{ github.sha }}

      - name: Build and push web image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: web
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/heroes-web:latest
            ghcr.io/${{ steps.vars.outputs.owner_lc }}/heroes-web:${{ github.sha }}

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            mkdir -p /srv/heroes-app
            cd /srv/heroes-app
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/${{ github.repository }}.git
            fi
            git fetch --depth=1 origin ${{ github.ref_name }}
            git checkout -f FETCH_HEAD

            cat > .deploy.env <<EOF
            APP_IMAGE=ghcr.io/${{ steps.vars.outputs.owner_lc }}/heroes-app:${{ github.sha }}
            WEB_IMAGE=ghcr.io/${{ steps.vars.outputs.owner_lc }}/heroes-web:${{ github.sha }}
            APP_URL=${{ secrets.APP_URL }}
            APP_KEY=${{ secrets.APP_KEY }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF

            docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME || github.actor }} -p ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}
            docker network inspect heroes-net >/dev/null 2>&1 || docker network create heroes-net

            set -a
            . .deploy.env
            set +a

            docker compose -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.prod.yml up -d

            docker image prune -f || true
